### ISSUE TITLE
Add `printRelativeTo`

### ISSUE THREAD

**Issue by natefaubion** [slamdata/purescript-pathy#27]
Sometimes you have a Sandboxed path, but it needs to be printed relative to some other directory, which may involve `../`. `relativeTo` does not handle `ParentIn` for security reasons, so it's not possible to print a path like this safely. Adding a `printRelativeTo` function would allow one to take an absolute sandboxed path, and print it relative to another arbitrary absolute path.

**Comment by garyb** [comment]
I think we can close this now as it's probably not as relevant as it was - sandboxing, `relativeTo` and printing of paths are all different now 🙂
